version: '3.8'

services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/fxapi
    depends_on:
      - redis
    command: go run cmd/http/main.go
  monitor-manager:
    build: .
    restart: always
    depends_on:
      - redis
    command: go run cmd/monitor-manager/main.go
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
volumes:
  redis_volume_data:
  redis_insight_volume_data:
  pg_data: