version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/fxapi
    command: go run cmd/http/main.go
  cache:
    image: imageName